# -*- coding: utf-8 -*-
"""Untitled11.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hGXGxCg5EcmRPdDU5UOWlAD_K0xQZ8yA
"""

import pandas as pd

# Load your files
meta = pd.read_csv("bodmas_metadata.csv")
category = pd.read_csv("bodmas_malware_category.csv")

# Merge
df = pd.merge(meta, category, left_on="sha", right_on="sha256", how="inner")
df = df[['family', 'category']].dropna()
df['label'] = 1  # all malicious

# Synthetic benign samples
benign_samples = pd.DataFrame({
    'family': ['benign_file'] * 1000,
    'category': ['benign'] * 1000,
    'label': [0] * 1000
})

# Combine both
dataset = pd.concat([df, benign_samples], ignore_index=True)

# Save to new CSV file
dataset.to_csv("bodmas_combined_dataset.csv", index=False)

print("✅ Saved new dataset as 'bodmas_combined_dataset.csv'")
print("Shape:", dataset.shape)
print("Label distribution:\n", dataset['label'].value_counts())

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.model_selection import train_test_split, StratifiedKFold, cross_val_score
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

# ===============================
# 1. Load the combined dataset
# ===============================
df = pd.read_csv("bodmas_combined_dataset.csv")

print("Dataset loaded successfully!")
print("Dataset shape:", df.shape)
print(df.head())

# ===============================
# 2. Encode Labels (already done in the previous step, keep for consistency if needed later)
# ===============================
# Assuming 'family', 'category', and 'label' columns are already present and correctly encoded in the combined dataset

# You might still need to encode 'family' and 'category' if they are not already
# based on the previous cell's output, they are not yet encoded in the CSV, so let's encode them here.
le_family = LabelEncoder()
df['family_encoded'] = le_family.fit_transform(df['family'])

le_category = LabelEncoder()
df['category_encoded'] = le_category.fit_transform(df['category'])


# ===============================
# 3. Visualizations
# ===============================
plt.figure(figsize=(6,4))
df['label'].value_counts().plot(kind='bar', color=['skyblue', 'salmon'])
plt.xticks([0,1], ['Benign', 'Malicious'], rotation=0)
plt.title('Class Distribution')
plt.xlabel('File Type')
plt.ylabel('Count')
plt.show()

plt.figure(figsize=(10,6))
sns.heatmap(df[['family_encoded', 'category_encoded', 'label']].corr(),
              cmap='coolwarm', annot=True)
plt.title('Feature Correlation Heatmap')
plt.show()

# ===============================
# 4. Train-Test Split + Scaling
# ===============================
X = df[['family_encoded', 'category_encoded']]
y = df['label']

# Check class balance
print("\nLabel Distribution:", np.bincount(y))


scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

X_train, X_test, y_train, y_test = train_test_split(
    X_scaled, y, test_size=0.25, random_state=42, stratify=y
)

# ===============================
# 5. Model Setup
# ===============================
models = {
    'Random Forest': RandomForestClassifier(n_estimators=100, random_state=42),
    'Gradient Boosting': GradientBoostingClassifier(random_state=42),
    'MLP': MLPClassifier(hidden_layer_sizes=(128, 64), max_iter=300, random_state=42)
}

cv = StratifiedKFold(n_splits=3, shuffle=True, random_state=42)
results = {}

# ===============================
# 6. Cross-Validation
# ===============================
print("\nCross-validation results:")
# Check if there is more than one class in y_train before performing cross-validation
if len(np.unique(y_train)) > 1:
    for name, model in models.items():
        scores = cross_val_score(model, X_train, y_train,
                                   cv=cv, scoring='accuracy')
        results[name] = np.mean(scores)
        print(f"{name}: {np.mean(scores):.3f}")
else:
    print("Skipping cross-validation as only one class is present in the training data.")


# ===============================
# 7. Ensemble Prediction
# ===============================
fitted_models = {}
for name, model in models.items():
    model.fit(X_train, y_train)
    fitted_models[name] = model

# Check if there is more than one class in y_test before performing ensemble prediction
if len(np.unique(y_test)) > 1:
    probas = [model.predict_proba(X_test)[:,1] for model in fitted_models.values()]
    ensemble_proba = np.mean(probas, axis=0)
    ensemble_pred = (ensemble_proba >= 0.5).astype(int)

    acc = accuracy_score(y_test, ensemble_pred)
    cm = confusion_matrix(y_test, ensemble_pred)

    print("\n✅ Ensemble Accuracy:", round(acc, 3))
    print("\nClassification Report:\n", classification_report(y_test, ensemble_pred))

    sns.heatmap(cm, annot=True, fmt='d', cmap='Blues')
    plt.title('Confusion Matrix - Ensemble')
    plt.xlabel('Predicted')
    plt.ylabel('Actual')
    plt.show()
else:
    print("\nSkipping ensemble prediction and evaluation as only one class is present in the test data.")


# ===============================
# 8. Feature Importance (Random Forest)
# ===============================
rf = RandomForestClassifier(n_estimators=100, random_state=42)
rf.fit(X_train, y_train)

importances = rf.feature_importances_
indices = np.argsort(importances)[::-1]
plt.figure(figsize=(8,5))
plt.bar(range(len(importances)), importances[indices],
          color='teal', edgecolor='black')
plt.xticks(range(len(importances)),
             ['family_encoded', 'category_encoded'], rotation=90)
plt.title('Feature Importance - Random Forest')
plt.tight_layout()
plt.show()